"""端到端测试。"""

from __future__ import annotations

import subprocess
import unittest
from pathlib import Path
from tempfile import TemporaryDirectory

from _helpers import PROJECT_ROOT, artifacts_from_source, compiler_available
from visual_basic_core_compiler.toolchain import ToolchainDriver


class EndToEndTests(unittest.TestCase):
    def test_example_compiles_to_ir_and_c(self) -> None:
        source = (PROJECT_ROOT / "examples" / "function_call.vb").read_text(encoding="utf-8")
        artifacts = artifacts_from_source(source)
        ir_text = "\n".join(instruction.opcode for instruction in artifacts.optimized_program.functions[0].instructions)
        c_text = ToolchainDriver("portable-c").emit_backend_text(artifacts.optimized_program)
        self.assertIn("label", ir_text)
        self.assertIn("Program__Twice", c_text)

    def test_all_example_sources_compile_to_ir_and_c(self) -> None:
        example_names = [
            "hello.vb",
            "arithmetic.vb",
            "if_else.vb",
            "elseif_chain.vb",
            "for_step.vb",
            "while_loop.vb",
            "function_call.vb",
            "fib.vb",
            "gcd.vb",
            "collatz_steps.vb",
            "prime_numbers.vb",
            "leetcode_palindrome_number.vb",
            "leetcode_climbing_stairs.vb",
            "select_case_demo.vb",
            "array_sum.vb",
            "array_max_scan.vb",
            "leetcode_two_sum_bruteforce.vb",
        ]
        driver = ToolchainDriver("portable-c")
        for filename in example_names:
            source = (PROJECT_ROOT / "examples" / filename).read_text(encoding="utf-8")
            artifacts = artifacts_from_source(source)
            self.assertTrue(artifacts.optimized_program.functions, filename)
            c_text = driver.emit_backend_text(artifacts.optimized_program)
            self.assertIn("Generated by Visual-Basic-Core-Compiler", c_text, filename)

    @unittest.skipUnless(compiler_available(), "requires clang or cc")
    def test_builds_and_runs_executable(self) -> None:
        source = """
        Module Program
            Sub Main()
                Dim i As Integer = 1
                For i = 1 To 3
                    Print(i)
                Next
            End Sub
        End Module
        """
        artifacts = artifacts_from_source(source)
        driver = ToolchainDriver("portable-c")
        with TemporaryDirectory() as temp_dir:
            output_path = Path(temp_dir) / "program"
            driver.build_executable(artifacts.optimized_program, output_path)
            completed = subprocess.run([str(output_path)], capture_output=True, text=True)
        self.assertEqual(completed.returncode, 0)
        self.assertEqual(completed.stdout.strip().splitlines(), ["1", "2", "3"])

    @unittest.skipUnless(compiler_available(), "requires clang or cc")
    def test_fibonacci_example_runs(self) -> None:
        self._assert_example_output("fib.vb", ["0", "1", "1", "2", "3", "5", "8", "13"])

    @unittest.skipUnless(compiler_available(), "requires clang or cc")
    def test_prime_numbers_example_runs(self) -> None:
        self._assert_example_output("prime_numbers.vb", ["2", "3", "5", "7", "11", "13", "17", "19"])

    @unittest.skipUnless(compiler_available(), "requires clang or cc")
    def test_gcd_example_runs(self) -> None:
        self._assert_example_output("gcd.vb", ["6", "21"])

    @unittest.skipUnless(compiler_available(), "requires clang or cc")
    def test_collatz_example_runs(self) -> None:
        self._assert_example_output(
            "collatz_steps.vb",
            ["7", "22", "11", "34", "17", "52", "26", "13", "40", "20", "10", "5", "16", "8", "4", "2", "1"],
        )

    @unittest.skipUnless(compiler_available(), "requires clang or cc")
    def test_leetcode_palindrome_example_runs(self) -> None:
        self._assert_example_output("leetcode_palindrome_number.vb", ["True", "False", "True"])

    @unittest.skipUnless(compiler_available(), "requires clang or cc")
    def test_leetcode_climbing_stairs_example_runs(self) -> None:
        self._assert_example_output("leetcode_climbing_stairs.vb", ["8"])

    @unittest.skipUnless(compiler_available(), "requires clang or cc")
    def test_hello_example_runs(self) -> None:
        self._assert_example_output("hello.vb", ["Hello from VB"])

    @unittest.skipUnless(compiler_available(), "requires clang or cc")
    def test_arithmetic_example_runs(self) -> None:
        self._assert_example_output("arithmetic.vb", ["9"])

    @unittest.skipUnless(compiler_available(), "requires clang or cc")
    def test_if_else_example_runs(self) -> None:
        self._assert_example_output("if_else.vb", ["big"])

    @unittest.skipUnless(compiler_available(), "requires clang or cc")
    def test_elseif_chain_example_runs(self) -> None:
        self._assert_example_output("elseif_chain.vb", ["three"])

    @unittest.skipUnless(compiler_available(), "requires clang or cc")
    def test_for_step_example_runs(self) -> None:
        self._assert_example_output("for_step.vb", ["5", "3", "1"])

    @unittest.skipUnless(compiler_available(), "requires clang or cc")
    def test_while_loop_example_runs(self) -> None:
        self._assert_example_output("while_loop.vb", ["0", "1", "2"])

    @unittest.skipUnless(compiler_available(), "requires clang or cc")
    def test_function_call_example_runs(self) -> None:
        self._assert_example_output("function_call.vb", ["12"])

    @unittest.skipUnless(compiler_available(), "requires clang or cc")
    def test_select_case_example_runs(self) -> None:
        self._assert_example_output("select_case_demo.vb", ["three", "match"])

    @unittest.skipUnless(compiler_available(), "requires clang or cc")
    def test_array_sum_example_runs(self) -> None:
        self._assert_example_output("array_sum.vb", ["20"])

    @unittest.skipUnless(compiler_available(), "requires clang or cc")
    def test_array_max_scan_example_runs(self) -> None:
        self._assert_example_output("array_max_scan.vb", ["9"])

    @unittest.skipUnless(compiler_available(), "requires clang or cc")
    def test_two_sum_bruteforce_example_runs(self) -> None:
        self._assert_example_output("leetcode_two_sum_bruteforce.vb", ["0", "1"])

    def _assert_example_output(self, filename: str, expected_lines: list[str]) -> None:
        source = (PROJECT_ROOT / "examples" / filename).read_text(encoding="utf-8")
        artifacts = artifacts_from_source(source)
        driver = ToolchainDriver("portable-c")
        with TemporaryDirectory() as temp_dir:
            output_path = Path(temp_dir) / "program"
            driver.build_executable(artifacts.optimized_program, output_path)
            completed = subprocess.run([str(output_path)], capture_output=True, text=True)
        self.assertEqual(completed.returncode, 0)
        self.assertEqual(completed.stdout.strip().splitlines(), expected_lines)


if __name__ == "__main__":
    unittest.main()
