"""模块说明：把语义稳定后的 VB AST 生成 Portable C。"""

from __future__ import annotations

from .. import ast_nodes as ast
from ..ir import IRProgram
from ..semantic import SemanticModel, VOID
from .typing import BackendMeta


def emit_portable_c(program: IRProgram, meta: BackendMeta) -> str:
    """把 VB 程序生成稳定、可编译的 Portable C 文本。"""

    if program.source_program is None or program.semantic_model is None:
        raise ValueError("portable C backend requires source_program and semantic_model")

    source = program.source_program
    semantic = program.semantic_model
    module_name = source.module.name

    lines = [
        "/* Generated by Visual-Basic-Core-Compiler.",
        " * First-generation backend emits normalized portable C. */",
        "",
        "#include <stdio.h>",
        "",
        "static void vb_print_int(int value) {",
        '    printf("%d\\n", value);',
        "}",
        "",
        "static void vb_print_double(double value) {",
        '    printf("%.15g\\n", value);',
        "}",
        "",
        "static void vb_print_string(const char *value) {",
        '    printf("%s\\n", value);',
        "}",
        "",
        "static void vb_print_bool(int value) {",
        '    printf("%s\\n", value ? "True" : "False");',
        "}",
        "",
    ]

    for member in source.module.members:
        lines.append(_render_prototype(module_name, member))
    if source.module.members:
        lines.append("")

    for member in source.module.members:
        lines.extend(_render_callable(module_name, member, semantic, meta))
        lines.append("")

    main_member = _find_main(source.module.members)
    if main_member is not None:
        lines.extend(_render_entry_point(module_name, main_member))
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def _render_prototype(module_name: str, member: ast.CallableDecl) -> str:
    """生成函数或过程的 C 原型声明。"""

    params = ", ".join(_render_param(param) for param in member.params) or "void"
    if isinstance(member, ast.SubDecl):
        return f"void {_c_function_name(module_name, member.name)}({params});"
    return f"{_c_type(member.return_type)} {_c_function_name(module_name, member.name)}({params});"


def _render_callable(
    module_name: str,
    member: ast.CallableDecl,
    semantic: SemanticModel,
    meta: BackendMeta,
) -> list[str]:
    """生成单个函数或过程的完整 C 实现。"""

    params = ", ".join(_render_param(param) for param in member.params) or "void"
    if isinstance(member, ast.SubDecl):
        signature = f"void {_c_function_name(module_name, member.name)}({params})"
    else:
        signature = f"{_c_type(member.return_type)} {_c_function_name(module_name, member.name)}({params})"

    lines = [f"/* backend target: {meta.target_name} */", signature + " {"]
    lines.extend(_render_block(module_name, member.body, semantic, 1))
    lines.append("}")
    return lines


def _render_block(module_name: str, body: list[ast.Statement], semantic: SemanticModel, indent: int) -> list[str]:
    """按顺序渲染语句块中的所有语句。"""

    lines: list[str] = []
    for stmt in body:
        lines.extend(_render_stmt(module_name, stmt, semantic, indent))
    return lines


def _render_stmt(module_name: str, stmt: ast.Statement, semantic: SemanticModel, indent: int) -> list[str]:
    """把单条高层语句翻译成对应的 C 代码片段。"""

    pad = "    " * indent
    if isinstance(stmt, ast.VarDeclStmt):
        line = pad + f"{_c_type(stmt.type_name)} {stmt.name}"
        if stmt.initializer is not None:
            line += f" = {_render_expr(module_name, stmt.initializer, semantic)}"
        return [line + ";"]
    if isinstance(stmt, ast.AssignmentStmt):
        return [pad + f"{stmt.name} = {_render_expr(module_name, stmt.value, semantic)};"]
    if isinstance(stmt, ast.ExpressionStmt):
        return [pad + _render_expr(module_name, stmt.expression, semantic) + ";"]
    if isinstance(stmt, ast.IfStmt):
        lines = [pad + f"if ({_render_expr(module_name, stmt.condition, semantic)}) {{"]
        lines.extend(_render_block(module_name, stmt.then_body, semantic, indent + 1))
        lines.append(pad + "}")
        if stmt.else_body is not None:
            lines.append(pad + "else {")
            lines.extend(_render_block(module_name, stmt.else_body, semantic, indent + 1))
            lines.append(pad + "}")
        return lines
    if isinstance(stmt, ast.WhileStmt):
        lines = [pad + f"while ({_render_expr(module_name, stmt.condition, semantic)}) {{"]
        lines.extend(_render_block(module_name, stmt.body, semantic, indent + 1))
        lines.append(pad + "}")
        return lines
    if isinstance(stmt, ast.ForStmt):
        loop_suffix = f"{stmt.line}_{stmt.column}"
        end_expr = _render_expr(module_name, stmt.end, semantic)
        step_expr = _render_expr(module_name, stmt.step, semantic) if stmt.step is not None else "1"
        lines = [
            pad + "{",
            pad + f"    int __vb_for_end_{loop_suffix} = {end_expr};",
            pad + f"    int __vb_for_step_{loop_suffix} = {step_expr};",
            pad
            + f"    for ({stmt.variable} = {_render_expr(module_name, stmt.start, semantic)}; "
            + f"(__vb_for_step_{loop_suffix} >= 0) ? ({stmt.variable} <= __vb_for_end_{loop_suffix}) : ({stmt.variable} >= __vb_for_end_{loop_suffix}); "
            + f"{stmt.variable} = {stmt.variable} + __vb_for_step_{loop_suffix}) {{",
        ]
        lines.extend(_render_block(module_name, stmt.body, semantic, indent + 1))
        lines.append(pad + "    }")
        lines.append(pad + "}")
        return lines
    if isinstance(stmt, ast.ReturnStmt):
        if stmt.value is None:
            return [pad + "return;"]
        return [pad + f"return {_render_expr(module_name, stmt.value, semantic)};"]
    raise AssertionError(f"unsupported statement type: {type(stmt)!r}")


def _render_expr(module_name: str, expr: ast.Expression, semantic: SemanticModel) -> str:
    """把表达式节点渲染成一段可嵌入的 C 表达式文本。"""

    if isinstance(expr, ast.IntegerLiteral):
        return str(expr.value)
    if isinstance(expr, ast.DoubleLiteral):
        return repr(expr.value)
    if isinstance(expr, ast.StringLiteral):
        return '"' + expr.value.replace("\\", "\\\\").replace('"', '\\"') + '"'
    if isinstance(expr, ast.BooleanLiteral):
        return "1" if expr.value else "0"
    if isinstance(expr, ast.NameExpr):
        return expr.identifier
    if isinstance(expr, ast.UnaryExpr):
        op = _c_unary_operator(expr.operator)
        return f"({op}{_render_expr(module_name, expr.operand, semantic)})"
    if isinstance(expr, ast.BinaryExpr):
        op = _c_binary_operator(expr.operator)
        return f"({_render_expr(module_name, expr.left, semantic)} {op} {_render_expr(module_name, expr.right, semantic)})"
    if isinstance(expr, ast.CallExpr):
        if expr.callee.lower() == "print":
            arg = expr.args[0]
            arg_type = semantic.expression_type(arg)
            rendered_arg = _render_expr(module_name, arg, semantic)
            if arg_type == "Integer":
                return f"vb_print_int({rendered_arg})"
            if arg_type == "Double":
                return f"vb_print_double({rendered_arg})"
            if arg_type == "String":
                return f"vb_print_string({rendered_arg})"
            if arg_type == "Boolean":
                return f"vb_print_bool({rendered_arg})"
            raise AssertionError(f"unsupported Print type: {arg_type}")
        args = ", ".join(_render_expr(module_name, arg, semantic) for arg in expr.args)
        return f"{_c_function_name(module_name, expr.callee)}({args})"
    raise AssertionError(f"unsupported expression type: {type(expr)!r}")


def _render_param(param: ast.Parameter) -> str:
    """生成单个参数的 C 形参声明文本。"""

    return f"{_c_type(param.type_name)} {param.name}"


def _c_type(type_name: str) -> str:
    """把 VB 类型映射到当前后端使用的 C 类型。"""

    if type_name == "Integer":
        return "int"
    if type_name == "Double":
        return "double"
    if type_name == "String":
        return "const char *"
    if type_name == "Boolean":
        return "int"
    if type_name == VOID:
        return "void"
    raise AssertionError(f"unsupported type: {type_name}")


def _c_unary_operator(operator: str) -> str:
    """把 VB 一元运算符映射到 C 运算符。"""

    if operator.lower() == "not":
        return "!"
    return operator


def _c_binary_operator(operator: str) -> str:
    """把 VB 二元运算符映射到 C 运算符。"""

    lowered = operator.lower()
    if lowered == "=":
        return "=="
    if lowered == "<>":
        return "!="
    if lowered == "and":
        return "&&"
    if lowered == "or":
        return "||"
    if lowered == "mod":
        return "%"
    return operator


def _c_function_name(module_name: str, name: str) -> str:
    """生成带模块前缀的稳定 C 符号名。"""

    return f"{module_name}__{name}"


def _find_main(members: list[ast.CallableDecl]) -> ast.CallableDecl | None:
    """查找是否存在可映射为程序入口的 `Main`。"""

    for member in members:
        if member.name.lower() == "main":
            return member
    return None


def _render_entry_point(module_name: str, member: ast.CallableDecl) -> list[str]:
    """在存在无参 Main 时生成宿主进程入口函数。"""

    c_name = _c_function_name(module_name, member.name)
    if member.params:
        return []
    if isinstance(member, ast.SubDecl):
        return [
            "int main(void) {",
            f"    {c_name}();",
            "    return 0;",
            "}",
        ]
    return [
        "int main(void) {",
        f"    return {c_name}();",
        "}",
    ]
